### ISSUE TITLE
Cannot precompile

### ISSUE THREAD

**Issue by Suavesito-Olimpiada** [Gnimuc/Assimp.jl#2]
If I try `using Assimp`, a long log happen it is caudef because of the assigment in the libassimp_common.jl, line 417, where s tries to set a bbigger than `Int32` in a `Int32`.

**Comment by Gnimuc** [comment]
I reworked the package and added a naive file-loading example: https://github.com/Gnimuc/Assimp.jl/blob/master/test/runtests.jl 

Since I'm not actively using this package, if you hit certain bugs, feel free to open a new issue. :)
